type: maniskill
name:
reconfiguration_freq: 1
partial_reset: true
asymmetric_obs: false
max_episode_steps: 50
stochastic_eval: true
has_final_obs: true

env_kwargs:
  obs_mode: state
  render_mode: rgb_array
  sim_backend: physx_cuda

vmin: -15
vmax: 15